<?php

namespace DryRun\Brands\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Support\Facades\Gate;
use DryRun\Brands\Models\Brand;

class BrandRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        // For store (create) action
        if ($this->isMethod('post')) {
             // Example: return Gate::allows('create', Brand::class);
             return true; // Replace with actual authorization logic
        }

        // For update action
        if ($this->isMethod('put') || $this->isMethod('patch')) {
            $brand = $this->route('brand'); // Assumes route model binding
            if (!$brand) {
                return false; // Or throw an exception if model not found
            }
            // Example: return Gate::allows('update', $brand);
            return true; // Replace with actual authorization logic
        }

        // For other methods like GET, DELETE, authorization is typically handled
        // by controller middleware or route definition, or within the policy for 'view'/'delete'.
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        $brand = $this->route('brand');
        $modelId = $brand ? $brand->id : null;

        // Basic rules are generated by the command based on schema.
        // Add custom rules or override generated ones here.
        // Example for BelongsToMany sync: 'tags' => 'nullable|array', 'tags.*' => 'integer|exists:tags,id'
        return [
            'name' => 'nullable|string|max:255',
            'team_id' => 'nullable|integer'
            // Example unique rule for update:
            // 'slug' => 'required|string|unique:brands,slug,' . $modelId . ',id',
        ];
    }

    /**
     * Get custom messages for validator errors.
     *
     * @return array
     */
    public function messages()
    {
        return [
            // 'title.required' => 'A title is required for the brand.',
            // 'tags.*.exists' => 'The selected tag is invalid.',
        ];
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array
     */
    public function attributes()
    {
        return [
            // 'title' => 'Brand Title',
            // 'body' => 'Brand Body Content',
        ];
    }

    /**
     * Handle a failed validation attempt.
     * API: Return JSON response. Web: Redirect back.
     *
     * @param  \Illuminate\Contracts\Validation\Validator  $validator
     * @return void
     *
     * @throws \Illuminate\Http\Exceptions\HttpResponseException|\Illuminate\Validation\ValidationException
     */
    protected function failedValidation(Validator $validator)
    {
        if ($this->expectsJson() || $this->is('api/*')) {
            throw new HttpResponseException(
                response()->json([
                    'message'   => 'The given data was invalid.',
                    'errors'    => $validator->errors(),
                ], 422)
            );
        }
        parent::failedValidation($validator);
    }
}
